// // actionType.js - Define all action types
// export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
// export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";

// // TAT (Turn Around Time)
// export const GET_TATS = "GET_TATS";
// export const ADD_NEW_TAT = "ADD_NEW_TAT";
// export const ADD_TAT_SUCCESS = "ADD_TAT_SUCCESS";
// export const ADD_TAT_FAIL = "ADD_TAT_FAIL";
// export const UPDATE_TAT = "UPDATE_TAT";
// export const UPDATE_TAT_SUCCESS = "UPDATE_TAT_SUCCESS";
// export const UPDATE_TAT_FAIL = "UPDATE_TAT_FAIL";
// export const DELETE_TAT = "DELETE_TAT";
// export const DELETE_TAT_SUCCESS = "DELETE_TAT_SUCCESS";
// export const DELETE_TAT_FAIL = "DELETE_TAT_FAIL";

// // Category Groups
// export const GET_CATEGORY_GROUPS = "GET_CATEGORY_GROUPS";
// export const ADD_NEW_CATEGORY_GROUP = "ADD_NEW_CATEGORY_GROUP";
// export const ADD_CATEGORY_GROUP_SUCCESS = "ADD_CATEGORY_GROUP_SUCCESS";
// export const ADD_CATEGORY_GROUP_FAIL = "ADD_CATEGORY_GROUP_FAIL";
// export const UPDATE_CATEGORY_GROUP = "UPDATE_CATEGORY_GROUP";
// export const UPDATE_CATEGORY_GROUP_SUCCESS = "UPDATE_CATEGORY_GROUP_SUCCESS";
// export const UPDATE_CATEGORY_GROUP_FAIL = "UPDATE_CATEGORY_GROUP_FAIL";
// export const DELETE_CATEGORY_GROUP = "DELETE_CATEGORY_GROUP";
// export const DELETE_CATEGORY_GROUP_SUCCESS = "DELETE_CATEGORY_GROUP_SUCCESS";
// export const DELETE_CATEGORY_GROUP_FAIL = "DELETE_CATEGORY_GROUP_FAIL";

// // Categories
// export const GET_CATEGORIES = "GET_CATEGORIES";
// export const ADD_NEW_CATEGORY = "ADD_NEW_CATEGORY";
// export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
// export const ADD_CATEGORY_FAIL = "ADD_CATEGORY_FAIL";
// export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
// export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
// export const UPDATE_CATEGORY_FAIL = "UPDATE_CATEGORY_FAIL";
// export const DELETE_CATEGORY = "DELETE_CATEGORY";
// export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
// export const DELETE_CATEGORY_FAIL = "DELETE_CATEGORY_FAIL";

// // Departments
// export const GET_DEPARTMENTS = "GET_DEPARTMENTS";
// export const ADD_NEW_DEPARTMENT = "ADD_NEW_DEPARTMENT";
// export const ADD_DEPARTMENT_SUCCESS = "ADD_DEPARTMENT_SUCCESS";
// export const ADD_DEPARTMENT_FAIL = "ADD_DEPARTMENT_FAIL";
// export const UPDATE_DEPARTMENT = "UPDATE_DEPARTMENT";
// export const UPDATE_DEPARTMENT_SUCCESS = "UPDATE_DEPARTMENT_SUCCESS";
// export const UPDATE_DEPARTMENT_FAIL = "UPDATE_DEPARTMENT_FAIL";
// export const DELETE_DEPARTMENT = "DELETE_DEPARTMENT";
// export const DELETE_DEPARTMENT_SUCCESS = "DELETE_DEPARTMENT_SUCCESS";
// export const DELETE_DEPARTMENT_FAIL = "DELETE_DEPARTMENT_FAIL";

// // Ticket actions
// export const GET_TICKETS = "GET_TICKETS";
// export const GET_TICKET_BY_ID = "GET_TICKET_BY_ID";
// export const GET_TICKETS_BY_ASSIGNED_ID = "GET_TICKETS_BY_ASSIGNED_ID";
// export const SELECTED_TICKET = "SELECTED_TICKET";

// // Add tickets
// export const ADD_NEW_TICKET = "ADD_NEW_TICKET";
// export const ADD_TICKET_SUCCESS = "ADD_TICKET_SUCCESS";
// export const ADD_TICKET_FAIL = "ADD_TICKET_FAIL";
// export const ADD_TICKET_RESET = "ADD_TICKET_RESET";

// // Edit tickets
// export const UPDATE_TICKET = "UPDATE_TICKET";
// export const UPDATE_TICKET_SUCCESS = "UPDATE_TICKET_SUCCESS";
// export const UPDATE_TICKET_FAIL = "UPDATE_TICKET_FAIL";

// // Assign tickets
// export const ASSIGN_TICKET = "ASSIGN_TICKET";
// export const ASSIGN_TICKET_SUCCESS = "ASSIGN_TICKET_SUCCESS";
// export const ASSIGN_TICKET_FAIL = "ASSIGN_TICKET_FAIL";

// // Delete tickets
// export const DELETE_TICKET = "DELETE_TICKET";
// export const DELETE_TICKET_SUCCESS = "DELETE_TICKET_SUCCESS";
// export const DELETE_TICKET_FAIL = "DELETE_TICKET_FAIL";

// // Ticket responses/details
// export const GET_TICKET_RESPONSES = "GET_TICKET_RESPONSES";
// export const ADD_TICKET_RESPONSE = "ADD_TICKET_RESPONSE";
// export const ADD_TICKET_RESPONSE_SUCCESS = "ADD_TICKET_RESPONSE_SUCCESS";
// export const ADD_TICKET_RESPONSE_FAIL = "ADD_TICKET_RESPONSE_FAIL";
// export const UPDATE_TICKET_RESPONSE = "UPDATE_TICKET_RESPONSE";
// export const UPDATE_TICKET_RESPONSE_SUCCESS = "UPDATE_TICKET_RESPONSE_SUCCESS";
// export const UPDATE_TICKET_RESPONSE_FAIL = "UPDATE_TICKET_RESPONSE_FAIL";
// export const DELETE_TICKET_RESPONSE = "DELETE_TICKET_RESPONSE";
// export const DELETE_TICKET_RESPONSE_SUCCESS = "DELETE_TICKET_RESPONSE_SUCCESS";
// export const DELETE_TICKET_RESPONSE_FAIL = "DELETE_TICKET_RESPONSE_FAIL";

// // Reset action
// export const RESET_ADD_UPDATE_NEW_TICKET = "RESET_ADD_UPDATE_NEW_TICKET";
