// Common actions
export const API_RESPONSE_SUCCESS = 'API_RESPONSE_SUCCESS';
export const API_RESPONSE_ERROR = 'API_RESPONSE_ERROR';

// Get
export const GET_TICKETS_CATEGORY_GROUPS = 'GET_TICKETS_CATEGORY_GROUPS';
export const SELECTED_TICKETS_CATEGORY_GROUP =
  'SELECTED_TICKETS_CATEGORY_GROUP';

// Add
export const ADD_NEW_TICKETS_CATEGORY_GROUP = 'ADD_NEW_TICKETS_CATEGORY_GROUP';
export const ADD_TICKETS_CATEGORY_GROUP_SUCCESS =
  'ADD_TICKETS_CATEGORY_GROUP_SUCCESS';
export const ADD_TICKETS_CATEGORY_GROUP_FAIL =
  'ADD_TICKETS_CATEGORY_GROUP_FAIL';
export const ADD_TICKETS_CATEGORY_GROUP_RESET =
  'ADD_TICKETS_CATEGORY_GROUP_RESET';

// Edit
export const UPDATE_TICKETS_CATEGORY_GROUP = 'UPDATE_TICKETS_CATEGORY_GROUP';
export const UPDATE_TICKETS_CATEGORY_GROUP_SUCCESS =
  'UPDATE_TICKETS_CATEGORY_GROUP_SUCCESS';
export const UPDATE_TICKETS_CATEGORY_GROUP_FAIL =
  'UPDATE_TICKETS_CATEGORY_GROUP_FAIL';

// Delete
export const DELETE_TICKETS_CATEGORY_GROUP = 'DELETE_TICKETS_CATEGORY_GROUP';
export const DELETE_TICKETS_CATEGORY_GROUP_SUCCESS =
  'DELETE_TICKETS_CATEGORY_GROUP_SUCCESS';
export const DELETE_TICKETS_CATEGORY_GROUP_FAIL =
  'DELETE_TICKETS_CATEGORY_GROUP_FAIL';

// Reset
export const RESET_ADD_UPDATE_TICKETS_CATEGORY_GROUP =
  'RESET_ADD_UPDATE_TICKETS_CATEGORY_GROUP';
