export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const API_ERROR = 'LOGIN_API_ERROR';

export const SOCIAL_LOGIN = 'SOCIAL_LOGIN';

export const RESET_LOGIN_FLAG = 'RESET_LOGIN_FLAG';

export const UPDATE_ROUTE_INFO = 'UPDATE_ROUTE_INFO';
export const UPDATE_BRANCH_STATUS = 'UPDATE_BRANCH_STATUS';
export const UPDATE_BRANCH_STATUS_SUCCESS = 'UPDATE_BRANCH_STATUS_SUCCESS';

export const UPDATE_USER_BRANCH = 'UPDATE_USER_BRANCH';
export const GET_USER_INVITE_INFO = 'GET_USER_INVITE_INFO';
export const GET_USER_INVITE_INFO_SUCCESS = 'GET_USER_INVITE_INFO_SUCCESS';
export const REGISTER_PORTAL_ADMIN = 'REGISTER_PORTAL_ADMIN';
export const REGISTER_PORTAL_ADMIN_SUCCESS = 'REGISTER_PORTAL_ADMIN_SUCCESS';

export const BULKUPLOAD_UPDATE_AVAILABLEROUTES =
  'BULKUPLOAD_UPDATE_AVAILABLEROUTES';

export const RESET_ADD_UPDATE_NEW_PORTALS = 'RESET_ADD_UPDATE_NEW_PORTALS';
